Решение задачи по созданию функции вычисления факториала
js-tasks-ru/jsbasic-20231109_radik5 pull request #2
Opened 2023-11-11 20:17 UTC by zainullin

2023-11-11 20:18 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-12 15:32 UTC, SinimaWath requested changes

2023-11-12 15:32 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    return n * factorial(n - 1);
Через рекурсию тоже можно :) Идеально, попробуй решить без рекурсии, а на циклах

2023-11-12 15:33 UTC, SinimaWath approved these changes

2023-11-12 15:34 UTC, merged