подсчет факториала через цикл
js-tasks-ru/jsbasic-20231109_radik5 pull request #3
Opened 2023-11-12 16:53 UTC by zainullin

2023-11-12 16:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-12 19:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-11-13 14:34 UTC, SinimaWath requested changes

2023-11-13 14:34 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Эти два условия можно сократить в одно: 
```
if (!name) {
  return false;
}

```

2023-11-13 14:34 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Стоит заменить на более подходящий метод:
```
if (name.includes(' ')) {
  return false;
}
```

2023-11-13 15:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-13 19:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-11-14 13:45 UTC, SinimaWath approved these changes

2023-11-14 13:45 UTC, merged