сделаны три задачи из модуля 2
js-tasks-ru/jsbasic-20231109_radik5 pull request #7
Opened 2023-11-19 15:27 UTC by zainullin

2023-11-19 15:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-20 10:52 UTC, SinimaWath requested changes

2023-11-20 10:52 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (!Number.isNaN(val) && isFinite(val)) {
isFinite, уже включает в себя проверку на NaN. Но isFinite - не включает проверку на typeof === number.

Поэтому из этих 2 факто стоит перевести на:
`if (typeof val === 'number' && isFinite(val))` 

Или использовать метод `Number.isFinite(val)`:
`if (Number.isFinite(val))`

2023-11-20 13:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-20 14:24 UTC, SinimaWath approved these changes

2023-11-20 14:25 UTC, merged